import { z } from "zod";
import { biInline } from "../i18n";
import { assertSafeOutboundUrl, redactUrlForOutput, safeKey } from "../security";
import type { Env } from "../types";

const COMPATIBILITY_DATE = "2026-06-27";

export const createChildWorkerSchema = {
  script_name: z.string().min(3).max(63).describe(biInline("Cloudflare Worker script name. Use lowercase letters, numbers and dashes.", "Назва Cloudflare Worker. Використовуйте lowercase літери, цифри й дефіси.")),
  template: z.enum(["webhook-forwarder"]).default("webhook-forwarder").describe(biInline("Safe child Worker template to deploy.", "Безпечний template дочірнього Worker для деплою.")),
  target_url: z.string().url().describe(biInline("HTTPS URL that the child Worker forwards POST/PUT/PATCH requests to, for example Make/Zapier/n8n.", "HTTPS URL, куди дочірній Worker форвардить POST/PUT/PATCH запити, наприклад Make/Zapier/n8n.")),
  description: z.string().max(500).optional().describe(biInline("Optional human-readable description.", "Опційний людський опис.")),
};

export const deployCustomChildWorkerSchema = {
  script_name: z.string().min(3).max(63).describe(biInline("Cloudflare Worker script name. Use lowercase letters, numbers and dashes.", "Назва Cloudflare Worker. Використовуйте lowercase літери, цифри й дефіси.")),
  description: z.string().min(1).max(500),
  tools: z.array(z.object({
    name: z.string().min(1).max(80),
    description: z.string().max(500).optional(),
    input_schema: z.record(z.string(), z.unknown()).optional(),
  })).min(1).max(30).describe(biInline("Tools exposed by this child Worker.", "Інструменти, які надає цей child Worker.")),
  source_code: z.string().min(20).max(120_000).describe(biInline("Custom JavaScript. It must assign exports.handlers = { toolName: async (args, env) => ... }.", "Кастомний JavaScript. Він має задати exports.handlers = { toolName: async (args, env) => ... }.")),
  allow_custom_code: z.boolean().describe(biInline("Must be true. This is a safety confirmation before deploying LLM-written code.", "Має бути true. Це підтвердження безпеки перед деплоєм коду, написаного LLM.")),
};

export async function createChildWorkerFromTemplate(env: Env, args: z.infer<z.ZodObject<typeof createChildWorkerSchema>>) {
  assertWorkerFactoryConfigured(env);

  const scriptName = normalizeScriptName(args.script_name);
  const targetUrl = assertSafeOutboundUrl(args.target_url);
  const source = childForwarderSource(targetUrl.toString(), args.description ?? biInline("Generated by OneAIWorkers", "Створено OneAIWorkers"));

  const payload = await deployModuleWorker(env, scriptName, source);
  const expectedUrl = expectedWorkersDevUrl(env, scriptName);

  return {
    script_name: scriptName,
    template: args.template,
    deployed: true,
    target_url: redactUrlForOutput(targetUrl),
    expected_workers_dev_url: expectedUrl,
    note: expectedUrl
      ? biInline("If your workers.dev subdomain is enabled, this URL should receive POST/PUT/PATCH requests and forward them to the configured target URL.", "Якщо ваш workers.dev subdomain увімкнений, цей URL має приймати POST/PUT/PATCH запити й форвардити їх у налаштований target URL.")
      : biInline("Set CF_WORKERS_DEV_SUBDOMAIN to show the expected workers.dev URL, or find the Worker URL in Cloudflare dashboard.", "Задайте CF_WORKERS_DEV_SUBDOMAIN, щоб показувати очікуваний workers.dev URL, або знайдіть Worker URL у Cloudflare dashboard."),
    cloudflare_result: payload,
  };
}

export async function deployCustomChildWorker(env: Env, args: z.infer<z.ZodObject<typeof deployCustomChildWorkerSchema>>) {
  assertWorkerFactoryConfigured(env);
  if (!args.allow_custom_code) {
    throw new Error(biInline("Custom child Worker deploy requires explicit allow_custom_code=true.", "Деплой кастомного child Worker потребує явного allow_custom_code=true."));
  }

  const scriptName = normalizeScriptName(args.script_name);
  validateCustomSource(args.source_code);
  const childToken = randomToken();
  const source = customChildWorkerSource(args.description, args.tools, args.source_code, childToken);
  const payload = await deployModuleWorker(env, scriptName, source);
  const expectedUrl = expectedWorkersDevUrl(env, scriptName);

  return {
    script_name: scriptName,
    template: "custom-child-worker",
    deployed: true,
    expected_workers_dev_url: expectedUrl,
    child_worker_protocol: {
      health: expectedUrl ? `${expectedUrl}/health` : "/health",
      tools_list: expectedUrl ? `${expectedUrl}/tools/list` : "/tools/list",
      tools_call: expectedUrl ? `${expectedUrl}/tools/call` : "/tools/call",
      auth_header: "x-oneaiworkers-child-token",
    },
    next_step: biInline(
      "Save this child Worker as a connector with save_connector using mode=child_worker, child_worker_url, and a Cloudflare Secret that contains the child token below.",
      "Збережіть цей child Worker як конектор через save_connector з mode=child_worker, child_worker_url і Cloudflare Secret, у якому буде child token нижче.",
    ),
    child_token_once: childToken,
    warning: biInline(
      "This token is shown once. Store it as a Cloudflare Secret, for example CHILD_CRM_TOKEN, then use that secret name in the connector config.",
      "Цей token показано один раз. Збережіть його як Cloudflare Secret, наприклад CHILD_CRM_TOKEN, і використайте назву secret у конфігу конектора.",
    ),
    cloudflare_result: payload,
  };
}

async function deployModuleWorker(env: Env, scriptName: string, source: string) {
  const accountId = String(env.CF_ACCOUNT_ID || "");
  const apiToken = String(env.CF_API_TOKEN || "");
  if (!accountId || !apiToken) throw new Error(biInline("Worker Builder is not configured.", "Worker Builder не налаштований."));

  const form = new FormData();
  form.append(
    "metadata",
    new Blob([JSON.stringify({ main_module: "index.mjs", compatibility_date: COMPATIBILITY_DATE, usage_model: "standard" })], { type: "application/json" }),
  );
  form.append("index.mjs", new Blob([source], { type: "application/javascript+module" }), "index.mjs");

  const response = await fetch(`https://api.cloudflare.com/client/v4/accounts/${accountId}/workers/scripts/${scriptName}`, {
    method: "PUT",
    headers: { authorization: `Bearer ${apiToken}` },
    body: form,
  });
  const payload = await response.json().catch(() => null);
  if (!response.ok) {
    throw new Error(`${biInline("Cloudflare API error", "Помилка Cloudflare API")} ${response.status}: ${JSON.stringify(payload)}`);
  }
  return payload;
}

function assertWorkerFactoryConfigured(env: Env) {
  if (!env.CF_ACCOUNT_ID || !env.CF_API_TOKEN) {
    throw new Error(biInline("Worker Builder is not configured. Set CF_ACCOUNT_ID and CF_API_TOKEN first.", "Worker Builder не налаштований. Спершу задайте CF_ACCOUNT_ID і CF_API_TOKEN."));
  }
}

function normalizeScriptName(name: string): string {
  return safeKey(name).replaceAll(":", "-").replaceAll("_", "-");
}

function expectedWorkersDevUrl(env: Env, scriptName: string): string | null {
  return env.CF_WORKERS_DEV_SUBDOMAIN ? `https://${scriptName}.${env.CF_WORKERS_DEV_SUBDOMAIN}.workers.dev` : null;
}

function validateCustomSource(source: string) {
  const blocked = [
    /eval\s*\(/i,
    /new\s+Function\s*\(/i,
    /WebSocket\s*\(/i,
    /connect\s*\(/i,
    /import\s*\(/i,
    /import\s+[^;]+from/i,
    /export\s+/i,
  ];
  for (const pattern of blocked) {
    if (pattern.test(source)) throw new Error(biInline("Custom source contains a blocked JavaScript pattern.", "Кастомний код містить заблокований JavaScript pattern."));
  }
  if (!source.includes("exports.handlers")) {
    throw new Error(biInline("Custom source must assign exports.handlers.", "Кастомний код має задавати exports.handlers."));
  }
}

function customChildWorkerSource(description: string, tools: unknown[], userSource: string, childToken: string): string {
  return `const DESCRIPTION = ${JSON.stringify(description)};
const TOOLS = ${JSON.stringify(tools)};
const CHILD_TOKEN = ${JSON.stringify(childToken)};
const exports = {};

${userSource}

function json(payload, status = 200) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" },
  });
}

function isAuthorized(request) {
  return request.headers.get("x-oneaiworkers-child-token") === CHILD_TOKEN;
}

async function readJson(request) {
  try { return await request.json(); } catch { return {}; }
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/health" && request.method === "GET") {
      return json({ ok: true, type: "oneaiworkers-child-worker", description: DESCRIPTION });
    }
    if (!isAuthorized(request)) return json({ ok: false, error: "Unauthorized" }, 401);
    if (url.pathname === "/tools/list" && request.method === "POST") {
      return json({ ok: true, tools: TOOLS });
    }
    if (url.pathname === "/tools/call" && request.method === "POST") {
      const body = await readJson(request);
      const name = String(body.name || "");
      const args = body.arguments || {};
      const handler = exports.handlers && exports.handlers[name];
      if (typeof handler !== "function") return json({ ok: false, error: "Tool not found" }, 404);
      try {
        const result = await handler(args, env, request);
        return json({ ok: true, data: result });
      } catch (error) {
        return json({ ok: false, error: String(error && error.message || error) }, 500);
      }
    }
    return json({ ok: false, error: "Not found" }, 404);
  }
};
`;
}

function childForwarderSource(targetUrl: string, description: string): string {
  return `const TARGET_URL = ${JSON.stringify(targetUrl)};
const DESCRIPTION = ${JSON.stringify(description)};

export default {
  async fetch(request) {
    if (request.method === "GET") {
      return new Response(JSON.stringify({
        ok: true,
        type: "oneaiworkers-child-worker",
        template: "webhook-forwarder",
        description: DESCRIPTION,
        message: {
          en: "Send POST, PUT, or PATCH requests to this Worker and it will forward them to the configured target URL.",
          uk: "Надсилайте POST, PUT або PATCH запити до цього Worker, і він форвардитиме їх у налаштований target URL."
        }
      }, null, 2), {
        headers: { "content-type": "application/json; charset=utf-8" }
      });
    }

    if (!["POST", "PUT", "PATCH"].includes(request.method)) {
      return new Response(JSON.stringify({ ok: false, error: { en: "Use POST, PUT, or PATCH.", uk: "Використовуйте POST, PUT або PATCH." } }), {
        status: 405,
        headers: { "content-type": "application/json; charset=utf-8" }
      });
    }

    const headers = new Headers();
    const contentType = request.headers.get("content-type");
    if (contentType) headers.set("content-type", contentType);
    headers.set("x-oneaiworkers-child", "webhook-forwarder");

    const response = await fetch(TARGET_URL, { method: request.method, headers, body: request.body });
    return new Response(await response.text(), {
      status: response.status,
      headers: { "content-type": response.headers.get("content-type") || "application/json; charset=utf-8" }
    });
  }
};
`;
}

function randomToken(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}
