import { z } from "zod";
import { biInline } from "../i18n";
import { assertSafeOutboundUrl, redactUrlForOutput, safeKey } from "../security";
import type { Env } from "../types";

export const createChildWorkerSchema = {
  script_name: z.string().min(3).max(63).describe(biInline("Cloudflare Worker script name. Use lowercase letters, numbers and dashes.", "Назва Cloudflare Worker. Використовуйте lowercase літери, цифри й дефіси.")),
  template: z.enum(["webhook-forwarder"]).default("webhook-forwarder").describe(biInline("Safe child Worker template to deploy.", "Безпечний template дочірнього Worker для деплою.")),
  target_url: z.string().url().describe(biInline("HTTPS URL that the child Worker forwards POST/PUT/PATCH requests to, for example Make/Zapier/n8n.", "HTTPS URL, куди дочірній Worker форвардить POST/PUT/PATCH запити, наприклад Make/Zapier/n8n.")),
  description: z.string().max(500).optional().describe(biInline("Optional human-readable description.", "Опційний людський опис.")),
};

export async function createChildWorkerFromTemplate(env: Env, args: z.infer<z.ZodObject<typeof createChildWorkerSchema>>) {
  if (!env.CF_ACCOUNT_ID || !env.CF_API_TOKEN) {
    throw new Error(biInline("Child Worker factory is not configured. Set CF_ACCOUNT_ID and CF_API_TOKEN first.", "Factory дочірніх Worker не налаштована. Спершу задайте CF_ACCOUNT_ID і CF_API_TOKEN."));
  }

  const scriptName = safeKey(args.script_name).replaceAll(":", "-").replaceAll("_", "-");
  const targetUrl = assertSafeOutboundUrl(args.target_url);
  const source = childForwarderSource(targetUrl.toString(), args.description ?? biInline("Generated by OneAIWorkers", "Створено OneAIWorkers"));

  const form = new FormData();
  form.append(
    "metadata",
    new Blob([JSON.stringify({ main_module: "index.mjs", compatibility_date: "2026-06-27", usage_model: "standard" })], { type: "application/json" }),
  );
  form.append("index.mjs", new Blob([source], { type: "application/javascript+module" }), "index.mjs");

  const response = await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}/workers/scripts/${scriptName}`, {
    method: "PUT",
    headers: { authorization: `Bearer ${env.CF_API_TOKEN}` },
    body: form,
  });
  const payload = await response.json().catch(() => null);
  if (!response.ok) {
    throw new Error(`${biInline("Cloudflare API error", "Помилка Cloudflare API")} ${response.status}: ${JSON.stringify(payload)}`);
  }

  const expectedUrl = env.CF_WORKERS_DEV_SUBDOMAIN ? `https://${scriptName}.${env.CF_WORKERS_DEV_SUBDOMAIN}.workers.dev` : null;

  return {
    script_name: scriptName,
    template: args.template,
    deployed: true,
    target_url: redactUrlForOutput(targetUrl),
    expected_workers_dev_url: expectedUrl,
    note: expectedUrl
      ? biInline("If your workers.dev subdomain is enabled, this URL should receive POST/PUT/PATCH requests and forward them to the configured target URL.", "Якщо ваш workers.dev subdomain увімкнений, цей URL має приймати POST/PUT/PATCH запити й форвардити їх у налаштований target URL.")
      : biInline("Set CF_WORKERS_DEV_SUBDOMAIN to show the expected workers.dev URL, or find the Worker URL in Cloudflare dashboard.", "Задайте CF_WORKERS_DEV_SUBDOMAIN, щоб показувати очікуваний workers.dev URL, або знайдіть Worker URL у Cloudflare dashboard."),
    cloudflare_result: payload,
  };
}

function childForwarderSource(targetUrl: string, description: string): string {
  return `const TARGET_URL = ${JSON.stringify(targetUrl)};
const DESCRIPTION = ${JSON.stringify(description)};

export default {
  async fetch(request) {
    if (request.method === "GET") {
      return new Response(JSON.stringify({
        ok: true,
        type: "oneaiworkers-child-worker",
        template: "webhook-forwarder",
        description: DESCRIPTION,
        message: {
          en: "Send POST, PUT, or PATCH requests to this Worker and it will forward them to the configured target URL.",
          uk: "Надсилайте POST, PUT або PATCH запити до цього Worker, і він форвардитиме їх у налаштований target URL."
        }
      }, null, 2), {
        headers: { "content-type": "application/json; charset=utf-8" }
      });
    }

    if (!["POST", "PUT", "PATCH"].includes(request.method)) {
      return new Response(JSON.stringify({ ok: false, error: { en: "Use POST, PUT, or PATCH.", uk: "Використовуйте POST, PUT або PATCH." } }), {
        status: 405,
        headers: { "content-type": "application/json; charset=utf-8" }
      });
    }

    const headers = new Headers();
    const contentType = request.headers.get("content-type");
    if (contentType) headers.set("content-type", contentType);
    headers.set("x-oneaiworkers-child", "webhook-forwarder");

    const response = await fetch(TARGET_URL, { method: request.method, headers, body: request.body });
    return new Response(await response.text(), {
      status: response.status,
      headers: { "content-type": response.headers.get("content-type") || "application/json; charset=utf-8" }
    });
  }
};
`;
}
